/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCalendar: typeof import('./components/calendar/AppCalendar.vue')['default']
    CalendarHeader: typeof import('./components/thecalendar/CalendarHeader.vue')['default']
    CalendarHeaderMobile: typeof import('./components/thecalendar/CalendarHeaderMobile.vue')['default']
    CalendarMonthDayItem: typeof import('./components/thecalendar/CalendarMonthDayItem.vue')['default']
    CalendarWeekdays: typeof import('./components/thecalendar/CalendarWeekdays.vue')['default']
    CalendarWeekdaysMobile: typeof import('./components/thecalendar/CalendarWeekdaysMobile.vue')['default']
    ManageTags: typeof import('./components/shiplockplanner/ManageTags.vue')['default']
    NewLockMap: typeof import('./components/shiplockplanner/NewLockMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShipCard: typeof import('./components/shiplockplanner/ShipCard.vue')['default']
    ShipList: typeof import('./components/shiplockplanner/ShipList.vue')['default']
    ShipListImport: typeof import('./components/shiplockplanner/ShipListImport.vue')['default']
    ShipListTable: typeof import('./components/shiplockplanner/ShipListTable.vue')['default']
    ShipListTableFilter: typeof import('./components/shiplockplanner/ShipListTableFilter.vue')['default']
    ShiplockMapItem: typeof import('./components/shiplockplanner/ShiplockMapItem.vue')['default']
    ShiplockMapTable: typeof import('./components/shiplockplanner/ShiplockMapTable.vue')['default']
    ShiplockPhaseItem: typeof import('./components/shiplockplanner/ShiplockPhaseItem.vue')['default']
    ShiplockPhaseTable: typeof import('./components/shiplockplanner/ShiplockPhaseTable.vue')['default']
    TagItem: typeof import('./components/shiplockplanner/TagItem.vue')['default']
    TheCalendar: typeof import('./components/thecalendar/TheCalendar.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}
